resources:
- manager.yaml
# TODO: Adding service account manually
- service_account.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: manager-config
  files:
  - controller_manager_config.yaml


