
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-aerospike-aerospike-com-v1alpha1-aerospikecluster
  failurePolicy: Fail
  name: maerospikecluster.kb.io
  rules:
  - apiGroups:
    - aerospike.aerospike.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - aerospikeclusters
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-aerospike-aerospike-com-v1alpha1-aerospikecluster
  failurePolicy: Fail
  name: vaerospikecluster.kb.io
  rules:
  - apiGroups:
    - aerospike.aerospike.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - aerospikeclusters
  sideEffects: None
