# permissions for end users to edit aerospikeclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aerospikecluster-editor-role
rules:
- apiGroups:
  - aerospike.aerospike.com
  resources:
  - aerospikeclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aerospike.aerospike.com
  resources:
  - aerospikeclusters/status
  verbs:
  - get
