# permissions for end users to view aerospikeclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aerospikecluster-viewer-role
rules:
- apiGroups:
  - aerospike.aerospike.com
  resources:
  - aerospikeclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - aerospike.aerospike.com
  resources:
  - aerospikeclusters/status
  verbs:
  - get
