# RoleBinding
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aerospike-kubernetes-operator
subjects:
- kind: ServiceAccount
  name: aerospike-kubernetes-operator
  namespace: aerospike
roleRef:
  kind: ClusterRole
  name: aerospike-kubernetes-operator
  apiGroup: rbac.authorization.k8s.io
